# Generated by Django 3.0.5 on 2020-04-18 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0002_remove_templatequestion_default_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='templatequestion',
            name='disclaimer',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='templatequestion',
            name='is_negotiable',
            field=models.BooleanField(default=False),
        ),
    ]
