# Generated by Django 3.0.5 on 2020-04-18 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0003_auto_20200418_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templatequestion',
            name='disclaimer',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
