# Generated by Django 3.0.5 on 2020-04-19 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0004_auto_20200418_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='templatesection',
            name='css_class',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
